import { and, desc, eq, inArray, isNull } from "drizzle-orm";
import { getDb } from "../../../db";
import { appSessions, chatMembers, chats, contacts, notifications, users } from "../../../db/schema";
import { getAppUser } from "../../server-auth";

function normalizePhone(value:string){const digits=value.replace(/\D/g,"");if(digits.length===10)return `7${digits}`;if(digits.length===11&&digits.startsWith("8"))return `7${digits.slice(1)}`;return digits.slice(-15)}
async function hashPhone(value:string){const normalized=normalizePhone(value);if(normalized.length<10)return null;const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(normalized));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(request:Request){const user=await getAppUser(request);if(!user)return null;await getDb().insert(users).values({id:user.userId,email:user.email,name:user.displayName,createdAt:Date.now()}).onConflictDoUpdate({target:users.id,set:{email:user.email,name:user.displayName}});return user}
async function online(userIds:string[]){if(!userIds.length)return new Set<string>();const since=Date.now()-120000;const rows=await getDb().select({userId:appSessions.userId,lastSeenAt:appSessions.lastSeenAt}).from(appSessions).where(inArray(appSessions.userId,userIds));return new Set(rows.filter(row=>row.lastSeenAt>=since).map(row=>row.userId))}

export async function GET(request:Request){try{const me=await auth(request);if(!me)return Response.json({error:"Требуется вход"},{status:401});const db=getDb();const links=await db.select().from(contacts).where(eq(contacts.ownerId,me.userId));const ids=links.map(link=>link.contactUserId);const people=ids.length?await db.select({id:users.id,name:users.name,email:users.email,phoneLast4:users.phoneLast4,status:users.status}).from(users).where(inArray(users.id,ids)):[];const [profile]=await db.select({userId:users.id,displayName:users.name,status:users.status,phoneLast4:users.phoneLast4,avatarData:users.avatarData}).from(users).where(eq(users.id,me.userId)).limit(1);const active=await online(ids);const alerts=await db.select().from(notifications).where(eq(notifications.userId,me.userId)).orderBy(desc(notifications.createdAt)).limit(30);return Response.json({contacts:people.map(person=>({...person,avatarUrl:`/api/avatar?id=${encodeURIComponent(person.id)}`,online:active.has(person.id)})),notifications:alerts,profile:{...profile,hasAvatar:Boolean(profile?.avatarData),avatarData:undefined}})}catch(error){return Response.json({error:error instanceof Error?error.message:"Ошибка контактов"},{status:500})}}

export async function POST(request:Request){try{const me=await auth(request);if(!me)return Response.json({error:"Требуется вход"},{status:401});const p=await request.json() as {action?:string;phone?:string;phoneHashes?:string[];targetUserId?:string;alias?:string;status?:string};const db=getDb();
 if(p.action==="set-profile"){await db.update(users).set({status:p.status?.trim().slice(0,120)||null}).where(eq(users.id,me.userId));return Response.json({ok:true})}
 if(p.action==="set-phone"){const phone=p.phone?.trim()||"";const phoneHash=await hashPhone(phone);if(!phoneHash)return Response.json({error:"Введите корректный номер телефона"},{status:400});const normalized=normalizePhone(phone);await db.update(users).set({phoneHash,phoneLast4:normalized.slice(-4)}).where(eq(users.id,me.userId));return Response.json({ok:true,last4:normalized.slice(-4)})}
 if(p.action==="sync-phonebook"){const hashes=[...new Set((p.phoneHashes||[]).filter(value=>/^[a-f0-9]{64}$/.test(value)))].slice(0,3000);if(!hashes.length)return Response.json({matches:[]});const rows=await db.select({id:users.id,name:users.name,phoneHash:users.phoneHash,phoneLast4:users.phoneLast4}).from(users).where(inArray(users.phoneHash,hashes));const existing=await db.select().from(contacts).where(eq(contacts.ownerId,me.userId));const saved=new Set(existing.map(x=>x.contactUserId));const ids=rows.map(x=>x.id);const active=await online(ids);return Response.json({matches:rows.filter(x=>x.id!==me.userId).map(x=>({...x,isContact:saved.has(x.id),online:active.has(x.id)}))})}
 if(p.action==="add-contact"){const target=p.targetUserId||"";if(!target||target===me.userId)return Response.json({error:"Некорректный контакт"},{status:400});const [person]=await db.select().from(users).where(eq(users.id,target)).limit(1);if(!person)return Response.json({error:"Пользователь не найден"},{status:404});const now=Date.now();await db.batch([db.insert(contacts).values({ownerId:me.userId,contactUserId:target,alias:p.alias?.trim().slice(0,80)||null,createdAt:now}).onConflictDoNothing(),db.insert(notifications).values({id:crypto.randomUUID(),userId:target,actorId:me.userId,kind:"contact_added",body:`${me.displayName} добавил(а) вас в контакты`,createdAt:now})]);return Response.json({ok:true,person:{id:person.id,name:person.name}})}
 if(p.action==="start-direct"){const target=p.targetUserId||"";const [person]=await db.select().from(users).where(eq(users.id,target)).limit(1);if(!person)return Response.json({error:"Пользователь не найден"},{status:404});const mine=await db.select({chatId:chatMembers.chatId}).from(chatMembers).where(eq(chatMembers.userId,me.userId));const theirs=await db.select({chatId:chatMembers.chatId}).from(chatMembers).where(eq(chatMembers.userId,target));const theirIds=new Set(theirs.map(x=>x.chatId));for(const row of mine){if(!theirIds.has(row.chatId))continue;const [room]=await db.select().from(chats).where(and(eq(chats.id,row.chatId),eq(chats.kind,"direct"))).limit(1);if(room){const members=await db.select().from(chatMembers).where(eq(chatMembers.chatId,row.chatId));if(members.length===2)return Response.json({chat:{...room,title:person.name}})}}const id=crypto.randomUUID(),now=Date.now();await db.batch([db.insert(chats).values({id,title:person.name,kind:"direct",createdBy:me.userId,createdAt:now}),db.insert(chatMembers).values({chatId:id,userId:me.userId,role:"owner",joinedAt:now}),db.insert(chatMembers).values({chatId:id,userId:target,role:"member",joinedAt:now}),db.insert(contacts).values({ownerId:me.userId,contactUserId:target,createdAt:now}).onConflictDoNothing()]);return Response.json({chat:{id,title:person.name,kind:"direct",createdAt:now}},{status:201})}
 if(p.action==="read-notifications"){await db.update(notifications).set({readAt:Date.now()}).where(and(eq(notifications.userId,me.userId),isNull(notifications.readAt)));return Response.json({ok:true})}
 return Response.json({error:"Неизвестное действие"},{status:400})}catch(error){return Response.json({error:error instanceof Error?error.message:"Ошибка контактов"},{status:500})}}
