import { and, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { phoneVerifications, users } from "../../../db/schema";
import { hashPhone, normalizePhone, sha256 } from "../../profile-utils";
import { createGuest, createSessionForUser, getAppUser, hashPassword, verifyPassword } from "../../server-auth";
export async function POST(request:Request){try{const body=await request.json().catch(()=>({})) as {action?:string;name?:string;phone?:string;password?:string;code?:string};const db=getDb();
 if(body.action==="login"){const phoneHash=await hashPhone(body.phone||"");if(!phoneHash)return Response.json({error:"Введите корректный номер"},{status:400});const [user]=await db.select().from(users).where(and(eq(users.phoneHash,phoneHash),eq(users.registrationCompleted,true))).limit(1);if(!user||!await verifyPassword(body.password||"",user.passwordHash))return Response.json({error:user&&!user.passwordHash?"Для старого аккаунта сначала задайте пароль по SMS":"Неверный номер или пароль"},{status:401});const token=await createSessionForUser(user.id);return Response.json({token,user:{userId:user.id,email:user.email,displayName:user.name}},{headers:{"set-cookie":`orbit_session=${encodeURIComponent(token)}; Path=/; Max-Age=31536000; HttpOnly; Secure; SameSite=Lax`}})}
 if(body.action==="request-password-code"){const phone=normalizePhone(body.phone||""),phoneHash=await hashPhone(phone);if(!phoneHash)return Response.json({error:"Введите корректный номер"},{status:400});const [user]=await db.select().from(users).where(and(eq(users.phoneHash,phoneHash),eq(users.registrationCompleted,true))).limit(1);if(!user)return Response.json({error:"Аккаунт с таким номером не найден"},{status:404});const random=new Uint32Array(1);crypto.getRandomValues(random);const code=String(100000+random[0]%900000),now=Date.now(),codeHash=await sha256(`${user.id}:${phone}:${code}`);await db.insert(phoneVerifications).values({userId:user.id,phone,phoneHash,codeHash,expiresAt:now+600000,attempts:0,createdAt:now}).onConflictDoUpdate({target:phoneVerifications.userId,set:{phone,phoneHash,codeHash,expiresAt:now+600000,attempts:0,createdAt:now}});if(process.env.SMS_PROVIDER_URL){const sent=await fetch(process.env.SMS_PROVIDER_URL,{method:"POST",headers:{"content-type":"application/json",...(process.env.SMS_PROVIDER_TOKEN?{"authorization":`Bearer ${process.env.SMS_PROVIDER_TOKEN}`}:{})},body:JSON.stringify({phone,code,message:`Orbit Connect: код для установки пароля ${code}`})});if(!sent.ok)return Response.json({error:"Сервис SMS временно недоступен"},{status:502})}return Response.json({ok:true,demoCode:process.env.SMS_PROVIDER_URL?undefined:code})}
 if(body.action==="reset-password"){const phone=normalizePhone(body.phone||""),phoneHash=await hashPhone(phone);if(!phoneHash)return Response.json({error:"Некорректный номер"},{status:400});const [user]=await db.select().from(users).where(eq(users.phoneHash,phoneHash)).limit(1),[verification]=user?await db.select().from(phoneVerifications).where(eq(phoneVerifications.userId,user.id)).limit(1):[];if(!user||!verification||verification.expiresAt<Date.now()||await sha256(`${user.id}:${phone}:${body.code||""}`)!==verification.codeHash)return Response.json({error:"Неверный или истёкший код"},{status:400});const password=body.password||"";if(password.length<6||!/[\p{L}]/u.test(password)||!/[0-9]/.test(password))return Response.json({error:"Пароль: минимум 6 знаков, буква и цифра"},{status:400});await db.batch([db.update(users).set({passwordHash:await hashPassword(password)}).where(eq(users.id,user.id)),db.delete(phoneVerifications).where(eq(phoneVerifications.userId,user.id))]);const token=await createSessionForUser(user.id);return Response.json({token})}
 const session=await createGuest(body.name);return Response.json(session,{status:201,headers:{"set-cookie":`orbit_session=${encodeURIComponent(session.token)}; Path=/; Max-Age=31536000; HttpOnly; Secure; SameSite=Lax`}})}catch(error){return Response.json({error:error instanceof Error?error.message:"Ошибка регистрации"},{status:500})}}
export async function GET(request:Request){const user=await getAppUser(request);return user?Response.json({user}):Response.json({error:"Сессия недействительна"},{status:401})}
