"use client";
import { ChangeEvent, KeyboardEvent, useEffect, useMemo, useRef, useState } from "react";

type Chat={id:string|number;name:string;initials:string;preview:string;time:string;unread?:number;online?:boolean;group?:boolean};
type Message={id:string|number;from:"me"|"them";text?:string;time:string;file?:{name:string;size:string;kind:string};reaction?:number;reply?:string};
type DirectoryUser={id:string;name:string;email:string};
const initialChats:Chat[]=[
 {id:1,name:"Команда продукта",initials:"КП",preview:"Лена: Макеты уже в чате",time:"12:41",unread:4,group:true},
 {id:2,name:"Анна Волкова",initials:"АВ",preview:"Отлично, созвонимся вечером",time:"11:20",online:true},
 {id:3,name:"Семья",initials:"С",preview:"Мама: Ждём вас в субботу ❤️",time:"10:04",unread:2,group:true},
 {id:4,name:"Михаил Орлов",initials:"МО",preview:"Документ готов",time:"вчера"},
 {id:5,name:"Поездка в Грузию",initials:"Г",preview:"Ира: Билеты стали дешевле",time:"вчера",group:true}
];
const initialMessages:Message[]=[
 {id:1,from:"them",text:"Доброе утро! Собрала финальные экраны приложения.",time:"12:28"},
 {id:2,from:"them",file:{name:"Мобильное приложение.fig",size:"18,4 МБ",kind:"FIG"},time:"12:29"},
 {id:3,from:"me",text:"Супер. Особенно нравится экран звонка — всё очень чисто.",time:"12:34"},
 {id:4,from:"them",text:"Спасибо! Макеты уже в чате. Посмотрите ещё тёмную тему 👀",time:"12:41",reaction:3}
];
function Avatar({chat,small=false}:{chat:Chat;small?:boolean}){return <div className={`avatar green ${small?"small":""}`}>{chat.initials}</div>}

function appFetch(input:RequestInfo|URL,init:RequestInit={}){
 const headers=new Headers(init.headers);const token=localStorage.getItem("orbit_session");
 if(token)headers.set("authorization",`Bearer ${token}`);
 return fetch(input,{...init,headers});
}

export default function Home(){
 const [chatList,setChatList]=useState(initialChats);const [activeChat,setActiveChat]=useState(initialChats[0]);const [messages,setMessages]=useState(initialMessages);const [draft,setDraft]=useState("");
 const [section,setSection]=useState<"chats"|"contacts"|"calls"|"settings">("chats");const [folder,setFolder]=useState<"all"|"unread"|"groups">("all");const [search,setSearch]=useState("");
 const [conversationOpen,setConversationOpen]=useState(false);const [details,setDetails]=useState(false);const [call,setCall]=useState<null|"audio"|"video">(null);const [muted,setMuted]=useState(false);const [camera,setCamera]=useState(true);
 const [reply,setReply]=useState<Message|null>(null);const [showPinned,setShowPinned]=useState(true);const [newGroup,setNewGroup]=useState(false);const [groupName,setGroupName]=useState("");const [members,setMembers]=useState<string[]>([]);const [directory,setDirectory]=useState<DirectoryUser[]>([]);const [serverUserId,setServerUserId]=useState("");const [serverReady,setServerReady]=useState(false);const [needsAuth,setNeedsAuth]=useState(false);const [toast,setToast]=useState("");const [notifications,setNotifications]=useState(true);const fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>undefined)},[]);
 useEffect(()=>{void (async()=>{try{let r=await appFetch("/api/sync",{cache:"no-store"});if(r.status===401){const auth=await fetch("/api/auth",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});if(!auth.ok){setNeedsAuth(true);return}const session=await auth.json();localStorage.setItem("orbit_session",session.token);r=await appFetch("/api/sync",{cache:"no-store"})}if(!r.ok){setNeedsAuth(true);return}const data=await r.json();const rooms:Chat[]=(data.chatList||[]).map((c:{id:string;title:string;kind:string;createdAt:number})=>({id:c.id,name:c.title,initials:c.title.slice(0,2).toUpperCase(),preview:c.kind==="group"?"Групповой чат":"Личный чат",time:new Date(c.createdAt).toLocaleDateString("ru-RU"),group:c.kind==="group"}));setServerUserId(data.user.userId);setDirectory(data.directory||[]);setServerReady(true);setNeedsAuth(false);setChatList(rooms);if(rooms[0]){setActiveChat(rooms[0]);await loadMessages(rooms[0],data.user.userId)}}catch{setNeedsAuth(true);notice("Сервер временно недоступен")}})()},[]);
 useEffect(()=>{if(!serverReady||!activeChat)return;const timer=window.setInterval(()=>void loadMessages(activeChat,serverUserId),2500);return()=>window.clearInterval(timer)},[serverReady,activeChat.id,serverUserId]);
 const filtered=useMemo(()=>chatList.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())&&(folder==="all"||(folder==="unread"&&c.unread)||(folder==="groups"&&c.group))),[chatList,search,folder]);
 const notice=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(""),2200)};
 const nav=(next:typeof section)=>{setSection(next);setConversationOpen(false)};
 async function loadMessages(chat:Chat,userId=serverUserId){if(!serverReady&&!userId)return;const r=await fetch(`/api/sync?chatId=${encodeURIComponent(String(chat.id))}`,{cache:"no-store"});if(!r.ok)return;const data=await r.json();setMessages((data.messages||[]).map((m:{id:string;senderId:string;body:string|null;kind:string;fileName:string|null;fileSize:number|null;replyTo:string|null;createdAt:number})=>({id:m.id,from:m.senderId===userId?"me":"them",text:m.body||undefined,reply:m.replyTo||undefined,file:m.kind==="file"?{name:m.fileName||"Файл",size:m.fileSize?`${(m.fileSize/1048576).toFixed(1)} МБ`:"",kind:(m.fileName?.split(".").pop()||"FILE").toUpperCase()}:undefined,time:new Date(m.createdAt).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})})))}
 function selectChat(chat:Chat){setActiveChat(chat);setConversationOpen(true);setSection("chats");if(serverReady)void loadMessages(chat);else if(chat.id!==1)setMessages([{id:chat.id,from:"them",text:chat.preview.replace(/^.*?: /,""),time:chat.time}])}
 async function send(){const text=draft.trim();if(!text)return;if(serverReady){const r=await fetch("/api/sync",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"send",chatId:String(activeChat.id),body:text,replyTo:reply?.id?String(reply.id):undefined})});if(!r.ok){notice("Сообщение не отправлено");return}await loadMessages(activeChat)}else setMessages(x=>[...x,{id:Date.now(),from:"me",text,reply:reply?.text||reply?.file?.name,time:new Date().toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}]);setDraft("");setReply(null)}
 async function attach(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(serverReady){const form=new FormData();form.set("file",f);form.set("chatId",String(activeChat.id));const r=await fetch("/api/files",{method:"POST",body:form});if(!r.ok){notice("Файл не отправлен");return}await loadMessages(activeChat)}else{const size=f.size>1048576?`${(f.size/1048576).toFixed(1)} МБ`:`${Math.ceil(f.size/1024)} КБ`;setMessages(x=>[...x,{id:Date.now(),from:"me",file:{name:f.name,size,kind:f.name.split(".").pop()?.toUpperCase()||"FILE"},time:"сейчас"}])}e.target.value="";notice("Файл отправлен")}
 function download(id:string|number,name:string){if(serverReady){const a=document.createElement("a");a.href=`/api/files?id=${encodeURIComponent(String(id))}`;a.download=name;a.click()}else{const blob=new Blob([`Демонстрационный файл «${name}» из Orbit Connect`],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name+".txt";a.click();URL.revokeObjectURL(url)}notice("Файл загружен")}
 async function voice(){const body="▶ ━━━━━  Голосовое · 0:03";if(serverReady){await fetch("/api/sync",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"send",chatId:String(activeChat.id),body})});await loadMessages(activeChat)}else setMessages(x=>[...x,{id:Date.now(),from:"me",text:body,time:"сейчас"}]);notice("Голосовое отправлено")}
 async function react(message:Message){if(serverReady)await fetch("/api/sync",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"react",chatId:String(activeChat.id),messageId:String(message.id),emoji:"🔥"})});setMessages(x=>x.map(y=>y.id===message.id?{...y,reaction:(y.reaction||0)+1}:y))}
 async function makeGroup(){const name=groupName.trim();if(!name)return;let group:Chat;if(serverReady){const r=await fetch("/api/sync",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create-chat",title:name,memberIds:members})});if(!r.ok){notice("Группа не создана");return}const data=await r.json();group={id:data.chat.id,name,initials:name.slice(0,2).toUpperCase(),preview:"Новая группа",time:"сейчас",group:true}}else group={id:Date.now(),name,initials:name.slice(0,2).toUpperCase(),preview:`Группа создана · ${members.length+1} участников`,time:"сейчас",group:true};setChatList(x=>[group,...x]);setActiveChat(group);setMessages([]);setNewGroup(false);setGroupName("");setMembers([]);setConversationOpen(true);notice("Группа создана")}
 const key=(e:KeyboardEvent<HTMLInputElement>)=>{if(e.key==="Enter")send()};
 return <main className="app-shell">
  <aside className="rail"><div className="brand">o/</div><nav>
   <button className={section==="chats"?"active":""} onClick={()=>nav("chats")}><span>▤</span><b>Чаты</b></button><button className={section==="contacts"?"active":""} onClick={()=>nav("contacts")}><span>♙</span><b>Контакты</b></button><button className={section==="calls"?"active":""} onClick={()=>nav("calls")}><span>☎</span><b>Звонки</b></button><button className={section==="settings"?"active":""} onClick={()=>nav("settings")}><span>⚙</span><b>Настройки</b></button>
  </nav><div className="profile-dot">МК</div></aside>
  <section className="inbox"><header className="inbox-head"><div><p>ORBIT / CONNECT</p><h1>{section==="chats"?"Сообщения":section==="contacts"?"Контакты":section==="calls"?"Звонки":"Настройки"}</h1></div><button className="round primary" onClick={()=>setNewGroup(true)}>＋</button></header>
   <label className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Поиск"/></label>
   {section==="chats"&&<><div className="folders"><button className={folder==="all"?"active":""} onClick={()=>setFolder("all")}>Все</button><button className={folder==="unread"?"active":""} onClick={()=>setFolder("unread")}>Новые</button><button className={folder==="groups"?"active":""} onClick={()=>setFolder("groups")}>Группы</button></div><div className="chat-list with-folders"><p className="eyebrow">ЧАТЫ · {filtered.length}</p>{filtered.map((c,i)=><button key={c.id} className={`chat-row ${activeChat.id===c.id?"selected":""}`} onClick={()=>selectChat(c)}><div className="avatar-wrap"><Avatar chat={c}/>{c.online&&<i/>}</div><div className="chat-copy"><strong>{i===0&&"⌁ "}{c.name}</strong><span>{c.preview}</span></div><div className="chat-meta"><time>{c.time}</time>{c.unread&&<em>{c.unread}</em>}</div></button>)}</div></>}
   {section==="contacts"&&<div className="simple-list"><p className="eyebrow">ЛЮДИ</p>{chatList.filter(c=>!c.group).map(c=><button key={c.id} className="chat-row" onClick={()=>selectChat(c)}><Avatar chat={c}/><div className="chat-copy"><strong>{c.name}</strong><span>{c.online?"в сети":"был(а) недавно"}</span></div></button>)}</div>}
   {section==="calls"&&<div className="simple-list"><p className="eyebrow">НЕДАВНИЕ</p>{chatList.slice(1,4).map((c,i)=><button key={c.id} className="chat-row" onClick={()=>{setActiveChat(c);setCall(i===1?"video":"audio")}}><Avatar chat={c}/><div className="chat-copy"><strong>{c.name}</strong><span>{i===2?"Пропущенный":"Исходящий"} · {c.time}</span></div><span className="call-glyph">↗</span></button>)}</div>}
   {section==="settings"&&<div className="settings-card"><div className="profile-large">МК</div><h2>Максим Крылов</h2><p>@maxim · +7 999 123-45-67</p><a className="apk-link" href="/orbit-connect-v2.apk" download>Скачать APK <span>Android ↗</span></a><button onClick={()=>{setNotifications(!notifications);notice(`Уведомления ${notifications?"выключены":"включены"}`)}}>Уведомления <span>{notifications?"Включены":"Выключены"} ›</span></button><button onClick={()=>notice("Настройки приватности открыты")}>Конфиденциальность <span>›</span></button><button onClick={()=>notice("Используется тема Orbit")}>Оформление <span>Orbit ›</span></button></div>}
  </section>
  <section className={`conversation ${conversationOpen?"open-mobile":""}`}><header className="conversation-head"><button className="mobile-back" onClick={()=>setConversationOpen(false)}>‹</button><div className="avatar-wrap"><Avatar chat={activeChat} small/>{activeChat.online&&<i/>}</div><div className="title"><strong>{activeChat.name}</strong><span>{activeChat.group?"участники группы":activeChat.online?"в сети":"был(а) недавно"}</span></div><div className="head-actions"><button onClick={()=>setCall("audio")}>☎</button><button onClick={()=>setCall("video")}>▣</button><button onClick={()=>setDetails(true)}>•••</button></div></header>
   {showPinned&&<div className="pinned"><b>ЗАКРЕПЛЕНО</b><span>Макеты приложения и план запуска</span><button onClick={()=>setShowPinned(false)}>×</button></div>}
   <div className="messages"><div className="day"><span>Сегодня</span></div>{messages.map(m=><div key={m.id} className={`message-line ${m.from}`}>{m.from==="them"&&<Avatar chat={activeChat} small/>}<div className={`bubble ${m.file?"file":""}`} onDoubleClick={()=>setReply(m)} title="Двойное нажатие — ответить">{m.reply&&<div className="reply-quote">{m.reply}</div>}{m.text&&<p>{m.text}</p>}{m.file&&<div className="file-card"><div className="file-icon">{m.file.kind}</div><div><strong>{m.file.name}</strong><span>{m.file.size} · Файл</span></div><button onClick={()=>download(m.id,m.file!.name)}>↓</button></div>}<time>{m.time} {m.from==="me"&&"✓✓"}</time>{m.reaction!==undefined&&<button className="reaction" onClick={()=>void react(m)}>🔥 {m.reaction}</button>}</div></div>)}</div>
   {reply&&<div className="reply-bar"><b>ОТВЕТ</b><span>{reply.text||reply.file?.name}</span><button onClick={()=>setReply(null)}>×</button></div>}
   <footer className="composer"><button onClick={()=>fileInput.current?.click()}>＋</button><input ref={fileInput} type="file" hidden onChange={attach}/><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={key} placeholder="Сообщение"/><button onClick={()=>setDraft(x=>x+"🙂")}>☺</button><button className={draft.trim()?"send ready":"send"} onClick={()=>void (draft.trim()?send():voice())}>{draft.trim()?"↑":"●"}</button></footer>
  </section>
  {details&&<aside className="details-panel"><button className="close" onClick={()=>setDetails(false)}>×</button><Avatar chat={activeChat}/><h2>{activeChat.name}</h2><p>{activeChat.group?"Групповой чат":"@orbit_user"}</p><div className="detail-actions"><button onClick={()=>notice("Звук переключён")}>🔔<span>Звук</span></button><button onClick={()=>notice("Поиск по чату готов")}>⌕<span>Поиск</span></button><button onClick={()=>notice("Добавлено в избранное")}>♡<span>Избранное</span></button></div><h3>Файлы и медиа</h3><div className="media-grid"><span>FIG</span><span>PDF</span><span>JPG</span></div></aside>}
  {call&&<div className="call-screen"><div className="call-noise"/><div className="call-person"><Avatar chat={activeChat}/><h2>{activeChat.name}</h2><p>{call==="video"?"Видеозвонок":"Аудиозвонок"} · соединение…</p></div>{call==="video"&&camera&&<div className="self-video"><span>Вы</span></div>}<div className="call-controls"><button className={muted?"off":""} onClick={()=>setMuted(!muted)}><b>{muted?"×":"♬"}</b><span>Микрофон</span></button><button className="hangup" onClick={()=>setCall(null)}><b>☎</b><span>Завершить</span></button><button className={!camera?"off":""} onClick={()=>setCamera(!camera)}><b>▣</b><span>Камера</span></button></div></div>}
  {newGroup&&<div className="modal-back" onMouseDown={e=>{if(e.target===e.currentTarget)setNewGroup(false)}}><div className="group-modal"><p>НОВОЕ СООБЩЕСТВО / 01</p><h2>Создать группу</h2><label>Название<input autoFocus value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="Например, Команда продаж"/></label><span>Выберите участников</span><div className="member-picks">{(serverReady?directory:chatList.filter(c=>!c.group).map(c=>({id:String(c.id),name:c.name,email:""}))).filter(u=>u.id!==serverUserId).map(u=><label key={u.id}><input type="checkbox" checked={members.includes(u.id)} onChange={()=>setMembers(x=>x.includes(u.id)?x.filter(id=>id!==u.id):[...x,u.id])}/><div className="avatar green small">{u.name.slice(0,2).toUpperCase()}</div><b>{u.name}</b></label>)}</div><div className="modal-actions"><button onClick={()=>setNewGroup(false)}>Отмена</button><button className="confirm" disabled={!groupName.trim()} onClick={()=>void makeGroup()}>Создать ↗</button></div></div></div>}
  {needsAuth&&<div className="auth-screen"><div className="brand">o/</div><p>ORBIT / CONNECT</p><h2>Нет соединения<br/>с сервером</h2><span>Не удалось создать защищённую сессию. Проверьте интернет и попробуйте снова.</span><a href="/">Повторить подключение ↗</a><small>Регистрация выполняется автоматически внутри приложения.</small></div>}
  {toast&&<div className="toast">{toast}</div>}
 </main>
}
